### ISSUE TITLE
Outgoing transactions / split coins

### ISSUE THREAD

**Issue by Jacek-ghub** [steppsr/getxchtxPS#7]
When an outgoing transaction is made, the original (bigger) coin is being split.  After this transaction, there is an incoming transaction with the reminder of the original coin.  When we just blindly sum all transactions, those reversed-split inbound coins inflate totals (unless some additional marking is being done).

It looks simple for a single split, for example, we send 1mojo that is marked as 10m coin split into 1m + 9m, and after that we receive that 9m back.  I cannot say that I see any markings on that return that would help to identify such inbound transaction as split-return (and ignored).  I think it is more complicated than that, as I also notice 1m send out twice, and it looked like in:9m, out:1m, out:1m.

I also looked at xchscan, but got even more confused.  Over there, the same transaction is marked as out:9m, out:8, out:1 - nothing inbound, so totals are lowered.

Did you notice such transactions?  Maybe you have a better explanation?

Update:
I found your explanation on chiaforum about it.  Looking at alltxs.json, I see those removals there as well, although it looks like those removals didn't migrate to the final file.  I will check it more in the morning.

**Comment by steppsr** [comment]
You are correct! I missed doing the math on the removals when I ported this over from the Bash version. This script is **supposed** to be totaling up any Removal coins and using that amount on any OUTGOING_TX transactions instead of the normal amount. It will definitely make a difference, exactly as you describe. I will fix that this morning and push an update. Thanks for the catch and letting me know!!

**Comment by Jacek-ghub** [comment]
By the way, when you save alltxs* files on Win side, could you force encoding to be ASCII.  By default, Win uses dbcs, and that confuses other utilities when using PHP on Linux (e.g., JSON, date, ...).  

`$fix | Out-File $scripthome/alltxs_fixed.json -Encoding ASCII `

Actually, when the output goes to the screen for the final results, those are also dbcs chars, and I am not sure whether that can be ASCII forced (I modified the code to take another command line param to save it to the file instead (maybe less flexible, but the output can be pure ASCII this way).

**Comment by steppsr** [comment]
If you wanted to make a pull request for that new command line param for save to file, I will review it. If not, I should be able to add that pretty easy. I think I originally had it that way and then changed it to be more consistent with the Bash version.

I will add the -Encoding ASCII switch to the Out-File. I wasn't aware of the dbcs issue.

**Comment by steppsr** [comment]
Working on this one, pointed out another issue where I wasn't outputting the incorrect variable for Removals in the Verbose output causing it to be blank. That will be fixed also.

**Comment by steppsr** [comment]
v0.2.0 just released and fixed this issue.

**Comment by Jacek-ghub** [comment]
I just run the script on Win.  I think that there are still 2 problems there.

First problem is that the intended outgoing transaction is not recorded (or I am missing it).  When I started chia, somehow I got 100 mojos.  Then I sent 1m to join a pool (I think).  So, we should see: 
1. in:100
2. out:split:99
3. out:split:perm:1
4. in:split:99

I don't see that #3 transaction in two different cases.

The second problem is from the tax point of view.  If we want to depend on data provided, we most likely need to exclude transactions #2 and #4, as that is just a coin split, not really a financial transaction.  (Although, I don't really know much about the IRS side, so that is just a guess.)  Still, most likely we would need to explain it to a CPA.  Maybe to mitigate it, those #2/4 transactions should have an additional flag (SPLIT_IN_TX, SPLIT_OUT_TX)?  Still, I am not sure whether it would be easy to pair those split transactions (yesterday, I could pair one, but not the other).

**Comment by steppsr** [comment]
For #1, the 1 mojo is the PlotNFT... meaning it doesn't leave your 'wallet' per se, it becomes the singleton for the plots, at least that was my understanding. You're not paying 1 mojo to Chia or anything like that so there isn't an outgoing for 1 mojo.

For #2, I need to be cautious here as I am not a tax professional, and this is not tax advice or tax software. This is simply a wallet extraction tool. Now that the disclaimer is out of the way... I'm not sure I understand you. You are viewing the CSV file and not the JSON right? The CSV file should be returning only the **amount** for all transactions except OUTGOING_TX. It isn't totaling the Additions (split coins) or anything like that. For the OUTGOING_TX, (now with this version) it is totaling the Removal amounts (because these are the coins spent) and using that Removal amount as the transaction amount. The "change" you get back if your spend coins are more than the amount for the transaction, come back to you in a new (and separate) transaction.

If you want me to review your specific case and are willing to send me the JSON and/or CSV, I will look at them. That's up to you, I know some people wouldn't want to share that type of info. My email on gmail is the same as my username on Github.

**Comment by Jacek-ghub** [comment]
For #2 what I was trying to say is whether you could add an additional marking to those split transactions.  Something like (the last field):
```
123456,0xb...2,07/09/2021 21:05:03,INCOMING_TX,0.000000000099,0,0,SPLIT_TX
123456,0xa...1,07/09/2021 21:05:03,OUTGOING_TX,0.0000000001,0,0,SPLIT_TX
```
The second one is the coin to be split, the first is what is left from that coin after split / deduction of outgoing value.

**Comment by steppsr** [comment]
The CSV has one row per transaction, not one row per coin. The amount can represent multiple coins.

In the two rows above, you had one transaction Outgoing for 100 mojos, I'm assuming when you created a PlotNFT. Since the cost of the PlotNFT is only 1 mojo, 99 mojos were returned to you. So you have two transactions, as I would expect, 100 out, 99 back as change. So the net for the transactions is 1 mojo. This is a simple example, but the transaction could use many more coins if the 'price' was higher. Let's say you were buying an NFT once they come out and it was 10 XCH. You most likely won't have a coin who's amount is over 10 XCH (at least not this early on) so you would need to spend multiple coins to cover the price, then all those Removals are "split" as you say into a coin to pay out and a coin to come back as change. I'm not sure why the Split Tx would be needed or what you are trying to do with it. But I guess every Outgoing would be a "split". The only way I could see to identify the incoming as a "split" would be multiple passes through the data, storing off the coin data, such as parent_coin_info, puzzle_hash, etc. until you can match that an incoming coin to the outgoing. 

Honestly, I don't know how that would be useful. But you are welcome to fork the code and make that add if you want. I probably would not pull it back into this project.
